---
title: "An intuitive Introduction to R"
author: "Okan Sarioglu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Willkommen! {.unnumbered}

Willkommen zu diesem R-Kurs! In diesem Kurs zeige ich dir den Workflow von Rohdaten bis zu deinen ersten eigenen Analysen in R. Als ich selbst Anfänger war, habe ich viele Kurse dieser Art ausprobiert. Dabei sind mir zwei Punkte aufgefallen, die meinen Lernprozess verlangsamt haben – und die ich in diesem Kurs bewusst anders machen möchte:

-   In vielen Kursen wurde zu Beginn viel zu viel Unnötiges vermittelt. Es ist beispielsweise nicht entscheidend, mehrere Varianten eines Befehls zu kennen – viel wichtiger ist es, ein Verständnis und eine Intuition für die Funktionsweise zu entwickeln.

Dieser Kurs war ursprünglich ein Tutorial für meine jüngeren Studierenden an der Universität. Dabei habe ich mir folgende Frage gestellt: Was müssen sie wissen, um eigenständig Datenanalysen mit R durchführen zu können? Die Antwort lautet: Sie brauchen ein Verständnis für den Workflow. Deshalb habe ich mich entschieden, einen Kurs zu konzipieren, der nicht unnötige Varianten von Funktionen zeigt, sondern erklärt, wie man eine konkrete Fragestellung systematisch analysiert.

-   Viele Kurse waren nicht reproduzierbar! Das liegt nicht direkt an den Kursen selbst. Es gibt Werkzeuge, um R-Skripte reproduzierbar zu machen. Allerdings sind diese Werkzeuge nicht besonders anfängerfreundlich. Autorinnen und Autoren solcher Kurse stehen daher vor einem Zielkonflikt: Entweder sie vermitteln Einsteigerinnen und Einsteigern unnötig komplexe Inhalte oder sie verzichten darauf und nehmen in Kauf, dass der Kurs nicht reproduzierbar ist.

Dieser Kurs ist anders! Hier kannst du die R-Skripte herunterladen, sie direkt auf deinem eigenen Gerät ausführen und den Kurs aktiv nachvollziehen, indem du den Code selbst ausführst. So erhältst du die originale Erfahrung, mit R zu arbeiten.

## Über diesen Kurs {.unnumbered}

### Voraussetzungen {.unnumbered}

-   `R` und RStudio. Du solltest die jeweils aktuellste Version von R und RStudio installieren. Wie das einfach funktioniert, wird [hier](https://posit.co/download/rstudio-desktop/ "Link zum Download von R") erklärt.

### Was sind `R` und `RStudio`? {.unnumbered}

`R` ist eine Programmiersprache, die speziell für statistische Analysen entwickelt wurde. `RStudio` ist die Standard-Entwicklungsumgebung (IDE), um mit R zu arbeiten.

### Warum `R`? {.unnumbered}

-   Kostenlos und Open Source  
-   Funktionalitäten für alle Schritte des Forschungsprozesses – von der Datenerhebung bis zur Datenanalyse  
-   Speziell für statistische Analysen entwickelte Programmiersprache  
-   Sehr aktive Community:  
-   z. B. die `R`-Community auf [StackOverflow](https://stackoverflow.blog/2017/10/10/impressive-growth-r/)  
-   z. B. *#rstats* auf Twitter  

### Was dich erwartet – und was nicht {.unnumbered}

In diesem Kurs lernst du:

-   Dich mit `R` und seiner grundlegenden Syntax vertraut zu machen  
-   Zentrale Befehle aus dem tidyverse-Paket  
-   Data Wrangling, Data Bridging, Data Munging und Data Manipulation  
-   Einen effizienten Workflow  
-   Eine kurze Einführung in grundlegende Datenanalyse und Explorative Datenanalyse (EDA)  

Du wirst **nicht** lernen:

-   Fortgeschrittene R-Anwendungen (z. B. Webscraping, quantitative Textanalyse etc.)

### Überblick über die Kursstruktur {.unnumbered}

**1. Die R-Umgebung**

-   Grundlegende Funktionalitäten (Berechnungen, Vektoren, Matrizen, Listen)  
-   Objektklassen  
-   Zugriff auf, Subsetting und Benennung von Objekten  

**2. Datenmanipulation**

-   Pipelines bzw. Piping  
-   Das tidyverse – dplyr  
-   Laden und Speichern von Daten  
-   Daten strukturieren: Umbenennen, Neuordnen, Subsetting und Selektieren  
-   Variablen transformieren  
-   Daten zusammenführen (Merging)  
-   Fehlende Werte  

**3. Explorative Datenanalyse / Deskriptive Statistik**

-   Standardkennzahlen (Mittelwert, Median, Standardabweichung usw.)  
-   Kontingenztafeln  
-   Korrelationen  
-   Arbeiten mit EDA-Paketen  

**4. Datenvisualisierung**

-   Das tidyverse – ggplot2  
-   Erstellung von Plots  
-   Visualisierung beliebiger Datenstrukturen  

**5. Datenanalyse**

-   Lineare Regression  
-   Modellgüte  
-   Hypothesentests mit R  
-   Multiple Regression  
-   Kategoriale Variablen  

**6. R-Programmierung**

-   For-Schleifen  
-   Die apply-Familie  
-   Eigene Funktionen  

## Über mich {.unnumbered}

Mein Name ist Okan und ich bin Data Scientist. Genauer gesagt ist Data Science mein Beruf – ursprünglich habe ich jedoch Politikwissenschaft studiert. Von Politik zu Daten? Meine Universität war stark auf empirische Forschung ausgerichtet, und die Politikwissenschaft bildete hier keine Ausnahme. Um politische Phänomene zu erklären, habe ich große Datensätze analysiert – und das war der spannendste Teil meines Studiums. Deshalb habe ich mich entschieden, Data Scientist zu werden. Und ich bin sehr glücklich mit dieser Entscheidung.

Werde Teil dieses Kurses! Bitte melde Fehler, Bugs oder Probleme im Code. Wenn du Ideen hast, wie sich dieser Kurs verbessern lässt, kontaktiere mich gerne über GitHub oder per E-Mail. Lass uns generell in Kontakt bleiben – folge mir auf GitHub und LinkedIn. Wenn dir der Kurs gefällt, teile deine Erfahrungen und empfehle ihn weiter!
